#ifndef SCRIPTDECK_RESOURCE_IDS_H
#define SCRIPTDECK_RESOURCE_IDS_H
#define IDR_SCRIPTDECK_LOGO 101
#define IDR_SCRIPTDECK_HOME 102
#define IDI_SCRIPTDECK_APP 201
#define IDI_SCRIPTDECK_DECK 202
#endif
